# Generated by Django 3.0.5 on 2020-04-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='porfolio_site',
            new_name='portfolio_site',
        ),
    ]
