# Generated by Django 3.0.5 on 2020-04-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20200426_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.FileField(blank=True, upload_to='profile_pics'),
        ),
    ]
